RA-16 - complete
MaximMiller/RecipeApp pull request #14
Opened 2024-09-13 07:45 UTC by MaximMiller

Импортировал 2 иконки сердца
в ImageButton сердца добавил рипл эффект при нажатии
в initUI добавил слушателя кликов на сердце и условия отображения

2024-09-13 20:14 UTC, ievetrovdev requested changes

2024-09-13 20:14 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        var isFavorite = false
Если перевернуть экран, то нажатая кнопка сбросится. Фрагмент пересоберется и initUI вызовется вновь

2024-09-13 20:14 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        val btnLike = binding.btnLike
лучше использовать просто binding.btnLike.apply{} в таком случае

2024-09-13 20:14 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +            } else btnLike.setImageResource(R.drawable.ic_heart_empty)
давай придерживаться какого-то единого стиля кода. Либо пишем однострочные условия оба со скобочками, либо оба без скобок

2024-09-13 20:14 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +                android:id="@+id/btnLike"
Обращу внимание на небольшую мелочь. btn префикс все таки подразумевает просто кнопку. Но здесь ImageButton и в коде лучше сразу понимать с каким типом работать, поэтому префикс здесь предлагаю использовать ib или типа того

2024-09-13 20:14 UTC, ievetrovdev commented
Иконки экспортируем только в векторе. Чтобы всегда четко отображались на любых разрешениях с любым масштабированием.

2024-09-16 07:01 UTC, MaximMiller commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        var isFavorite = false
Переопределил методы onSaveInstanceState - добавил сохранение состояние на кнопку Лайк.
 и onCreate - проверят если нет сохраненного состояния то кнопка лайка по дефолту - false

2024-09-17 09:59 UTC, ievetrovdev commented
Этот коммент не поправил, сейчас твоя икона сердца в формате png, а не svg
<img width="776" alt="Снимок экрана 2024-09-17 в 12 59 10" src="https://github.com/user-attachments/assets/ba17ac25-b7cd-43f7-a7bc-f2d0a9f1f6b3">

2024-09-19 12:17 UTC, ievetrovdev approved these changes
Теперь всё корректно и по тз! Молодец!

2024-09-19 13:00 UTC, merged