RA-17 - complete
MaximMiller/RecipeApp pull request #15
Opened 2024-10-02 08:17 UTC by MaximMiller

Добавил методы:
saveFavorites()  сохранить в переменную sharedPrefs
метод getFavorites()  возвращает полученную из хранилища изменяемую коллекцию MutableSet<String>

2024-10-02 17:10 UTC, ievetrovdev requested changes
Пока функционал не работает (при повторном заходе изображение сердечка не закрашено). После избавления от локального isFavorite должен исправиться

2024-10-02 17:10 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +                isFavorite = true
Эта строчка выполнится, только при условии isFavorite(= true). Эта строка просто лишняя

2024-10-02 17:10 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +                isFavorite = false
Лишняя строка

2024-10-02 17:10 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +            if (isFavorite) {
Лучше вообще избавиться от этой локальной переменной-флага и каждый раз обращаемся к хранилищу, чтобы проверить наличие там необходимого Set'a айдишников.

2024-10-02 17:10 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        val editor = sharedPrefs?.edit()
Можно объединить через with(sharedPrefs.edit())

2024-10-02 17:10 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +private const val FAVORITES_KEY = "favorites"
Когда ты пишешь const val просто за пределами класса, значение становится глобальной переменной, которая является частью всего модуля, а не конкретного класса. Нарушается инкапсуляция.
Все константы должны быть прописаны внутри companion object класса, а не за его пределами

2024-11-12 20:20 UTC, Churickoid approved these changes
Всё верно исправил, молодец!

2024-11-13 05:16 UTC, merged