RA-18 - complete
MaximMiller/RecipeApp pull request #16
Opened 2024-11-14 17:47 UTC by MaximMiller

- Сверстал лейаут для фрагмента с RecyclerView
- Добавил метод loadFavoriteRecipes() в котором есть условие отображения ресайклера с избранными(showRecipes()) или заглушки(showStub())
- в фрагмент FavoritesFragment добавил метод getFavorites()
- в адаптер RecipesListAdapter добавил метод обновления updateRecipes()

2024-11-15 16:27 UTC, Churickoid requested changes
По текущему заданию всё ок, молодец! Надо поправить проблемы с прошлого ПР. 
Попробуй на экране Рецептов добавить и убрать из избранного элемент. Не получится, надо поискать причину в логике онКликЛистенера. Если самостоятельно не поулчится, я помогу.
Иконка сердце гораздо меньше чем на макете фигма, поправь по макету

2024-11-15 16:27 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
>      companion object {
Компоньон обжект принято хранить в самом конце класса

2024-11-15 16:27 UTC, Churickoid commented on app/src/main/res/layout/fragment_favorites.xml
> +        android:textSize="18sp"
Вынести в ресурсы, а лучше еще и в стиль

2024-11-16 07:07 UTC, MaximMiller commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
>      companion object {
+

2024-11-16 07:07 UTC, MaximMiller commented on app/src/main/res/layout/fragment_favorites.xml
> +        android:textSize="18sp"
+

2024-11-16 07:09 UTC, MaximMiller commented
Иконка hearts - согласно макета 24х24 - скорее всего в макете где сердечко 40х40 ошибка - тк 24х24 вынесены отдельно в 2-ух состояниях

2024-11-16 07:16 UTC, MaximMiller commented
Добавил изменения состояния isFavorite - спасибо - не досмотрел)

2024-11-16 16:52 UTC, Churickoid approved these changes
Всё верно, апрувлю.
Основная особенность векторного изображения, что вне зависимости от пикселей, оно будет корректно скейлится и выглядеть одинаково. На макете оно 40x40. Нужно импортировать SVG в нужном для нас размере. Поправь иконку в следующем ПР.
![image](https://github.com/user-attachments/assets/47a606b0-3e3f-47e8-b9e4-5cba9d5d1de5)

2024-11-16 17:15 UTC, merged