RA_23 complete
MaximMiller/RecipeApp pull request #19
Opened 2024-11-20 21:21 UTC by MaximMiller

создал функцию loadRecipe() - хранит стейт рецепта
изменил функцию initUI() - повесил слушателя изменений в рецепте, перенес логику из функции initRecycler(),
в RecipeViewModel перенес логику:
 добавления/получения в избранное, проверки рецепта на избранность

2024-11-21 19:53 UTC, Churickoid requested changes
Сейчас на экране Избранного всегда открывается Классический бургер, это связанно из-за того, что ты кладешь recipe а не id

2024-11-21 19:53 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +                    dividerInsetEnd = resources.getDimensionPixelSize(R.dimen.text_size_small)
Внутри наблюдателя observer должны находится только те данные, которые зависят от стейта. Из-за этого появился баг, попробуй нажать на иконку Сердца несколько раз, каждый раз будет добавляться новый divider и твой список будет раздуваться. Также вынеси из observer надо сам listener. Внутри observer оставить из функции ресайклера всё что зависит от значения recipe

2024-11-21 19:53 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +            )
Выстави количество порций и переверни экран. Оно из-за этого места выставится в 1 по стандарту. Мы добавляли viewModel, чтобы созхранять все параметры экрана.  В конструктор liveData у private val _recipeState передай дефолтный RecipeState, а во всех частях кода мы меняем только через .copy(), чтоб таких ситуаций не было

2024-11-21 19:53 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +        _recipeState.value = RecipeState(isFavorite = false)
Это были тестовые строки, их можно уже убрать

2024-11-24 19:07 UTC, MaximMiller commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +            )
+

2024-11-24 19:07 UTC, MaximMiller commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +        _recipeState.value = RecipeState(isFavorite = false)
+

2024-11-24 19:16 UTC, MaximMiller commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +                    dividerInsetEnd = resources.getDimensionPixelSize(R.dimen.text_size_small)
+

2024-11-24 21:27 UTC, Churickoid approved these changes
Молодец, всё верно! Интересно, что сейчас решил использовать Glide. Мы еще через уроков 15 будем её проходить и по урокам это не требовалось, но если понимаешь принцип работы - то оставляй

2024-11-26 17:14 UTC, merged