RA_25 complete
MaximMiller/RecipeApp pull request #21
Opened 2024-11-27 19:43 UTC by MaximMiller

в метод setupSeekBar()  добавил отправку изменения состояния стейта  по полю portionCount 
добавил метод onPortionsCountChanged() который на стороне RecipeViewModel() меняет стейт по полю portionCount 
в метод updateUI() добавил обновления ресайклера ингредиентов в зависимости от положение SeekBar

2024-11-28 19:12 UTC, Churickoid requested changes

2024-11-28 19:12 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
>                  binding.tvCountPortion.text = progress.toString()
Текст мы меняем в observer, когда пришел новый стейт. Здесь это делать не нужно

2024-11-28 19:12 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +            private var lastProgress = 1
Внутри фрагмента никакие данные запоминаться не должны, при повороте экрана - всё сотрется. Вся работа с данные происходит во viewModel

2024-11-28 19:12 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +                state.imageUrl?.let { imageUrl ->
Поскольку ты делаешь через glide, imageUrl хранится и так всегда внутри recipe. Заводить отдельную переменную под неё не нужно. Лучше её убрать вообще.  И на будущее такая двойная вложенность let не очень красиво выглядит, лучше тогда уже делать через if с &&

2024-11-28 19:12 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        if (!::ingredientsAdapter.isInitialized) {
Обращаться к Рефлексии (методы, которые работают с мета-данными) всегда плохо, это достаточно тяжелые операции, они ухудшают производительность байт кода.
Давай просто по умолчанию делать IngredientsAdapter с пустым листом и через метод менять его dataSet

2024-12-01 18:16 UTC, Churickoid approved these changes
Молодец, по заданию всё верно! Поправь коммент в следующем ПР по оптимизации приложения

2024-12-01 18:16 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        binding.rvIngredients.adapter = ingredientsAdapter
Каждый раз при измении стейта - будет создаваться новый объект адаптера. Плодить множество объектов не очень правильно, нужно менять существующий. Вне обсервера мы прикрепляем пустой адаптер к ресайклер вью  - внутри вызываем только updateIngredients

2024-12-01 18:56 UTC, MaximMiller commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        binding.rvIngredients.adapter = ingredientsAdapter
Поправил: теперь ingredientsAdapter инициализируется пустым листом в setupRecyclerView

2024-12-01 18:56 UTC, merged