RA-07 - complete
MaximMiller/RecipeApp pull request #5
Opened 2024-07-18 08:44 UTC by MaximMiller

Добавил верстку - заголовка на Фрагменте категории
Добавил RecyclerView с item CardView

2024-07-18 18:14 UTC, ievetrovdev requested changes

2024-07-18 18:14 UTC, ievetrovdev commented on app/src/main/res/drawable/ripple_effect.xml
> +<?xml version="1.0" encoding="utf-8"?>
Есть простой набор атрибутов, чтобы ripple эффект для элемента заработал:
android:foreground = "?selectableItemBackground"
android:clickable = "true"
android:focusable = "true"

2024-07-18 18:14 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">20sp</item>
ресурсы

2024-07-18 18:14 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_list_categories.xml
> +        android:layout_marginVertical="8dp"
ресурсы

2024-07-18 18:14 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_list_categories.xml
> +            android:layout_marginStart="16dp"
ресурсы!

2024-07-18 18:14 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_list_categories.xml
> +        android:layout_height="224dp">
ресурсы

2024-07-18 18:14 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_list_categories.xml
> +        <ImageView
Для изображения в шапке экрана тоже надо добавить contentDescription. Пусть описание говорит о том, что это изображение экрана с категориями.

2024-07-18 18:14 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +    android:layout_marginVertical="8dp"
Напоминаю, все размеры в разметке выносим в ресурсы. Давай пересмотрим еще раз все захардкоженные атрибуты.

2024-07-18 18:14 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +    android:layout_height="220dp"
Фиксированной высотой лучше делать только изображение. Сама карточка, текстовые поля – пусть будут адаптивными по размеру контента. Мы не знаем какой длины будут тексты, и если будет больше того, что в макете – текст упрется в грань карточки.

2024-07-18 18:14 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +    android:layout_width="156dp"
Обрати внимание карточка не на всю ширину. Айтем должен занимать всю ширину лейаута (родителя). Фактически сам лейаут и является карточкой. Эти карточки заполняются заполняют ресайклер по описанным правилам расположения.

2024-07-18 18:14 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_list_categories.xml
> +            android:layout_width="149dp"
Ничего не хардкодим. Текст может отличаться на разных языках, например. Такие элементы делаются строго по размеру контента.

2024-07-18 18:14 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_list_categories.xml
> +            android:layout_marginTop="164dp"
У тебя есть основной размер отступа 16dp слева и снизу – это все что нужно соблюсти. Это все грани, где потребуется привязка констрейнтами.

2024-07-20 11:55 UTC, ievetrovdev requested changes

2024-07-20 11:55 UTC, ievetrovdev commented on app/src/main/res/drawable/ripple_effect.xml
> +        android:clickable="true"
имею в виду набор атрибутов для вьюхи просто

2024-07-20 11:55 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="cv_corner_radius_item_category">8dp</dimen>
Повторять одни и те же значения размеров с разными айдишниками не рекомендуется. Пусть в dimens хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-07-20 11:55 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="iv_screenshot_of_the_categories">Это изображение для категории</string>
Для категории какой? Динамически указываем во фрагменте

2024-07-20 11:55 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
>      <string name="title_favorite_fragment">Фрагмент списка избранных</string>
А кому мы говорим, что это фрагмент? Пользователю?)

2024-07-20 11:55 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
А где в карточке изображение, заголовок и описание категории?)

2024-07-20 11:55 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_list_categories.xml
> +        app:spanCount="2"
Отсутствует форматирование лейаута. Атрибуты описаны в разном порядке

2024-07-20 11:55 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
Добавь с фейковыми данными какого-то рецепта, чтобы отображалось только для разработчика на превью

2024-07-23 10:57 UTC, MaximMiller commented on app/src/main/res/values/strings.xml
> +    <string name="iv_screenshot_of_the_categories">Это изображение для категории</string>
Вот это я не понял - что нужно сделать?

2024-07-23 19:31 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="iv_screenshot_of_the_categories">Это изображение для категории</string>
Задавать динамически из фрагмента. Это изображение категории название_категории.

2024-07-23 19:36 UTC, ievetrovdev requested changes

2024-07-23 19:36 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/CategoriesListFragment.kt
> +    private var currentCategory: String = "Default Category"
это чего такое?)

2024-07-23 19:36 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
>      <string name="tv_heading">Кaтегории</string>
У тебя уже есть эта строка, нужно переиспользовать

2024-07-23 19:36 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="iv_screenshot_of_the_categories">Это изображение для категории</string>
А нет, видишь непонятно название и назначение (и почему скриншот). Это изображение в шапке для экрана со списком категорий

2024-07-23 19:36 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="cv_corner_radius_item_category">8dp</dimen>
не исправлено

2024-07-24 18:28 UTC, MaximMiller commented on app/src/main/res/values/dimens.xml
> +    <dimen name="cv_corner_radius_item_category">8dp</dimen>
исправлено в ea88bef6ecc2a842a06328a68351119e8361cf06

2024-07-25 05:26 UTC, MaximMiller commented on app/src/main/res/values/dimens.xml
> +    <dimen name="cv_corner_radius_item_category">8dp</dimen>
![image](https://github.com/user-attachments/assets/bd0cf54f-82d5-499d-b275-0cfd50e1aca6)

2024-07-25 08:10 UTC, ievetrovdev requested changes

2024-07-25 08:10 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +    app:cardForegroundColor="@drawable/ripple_effect"
Добавив атрибуты кликательности выше дополнительный drawable уже не требуется. По умолчанию ripple отрабатывает корректно.

2024-07-25 08:10 UTC, ievetrovdev commented on app/src/main/res/values-en/strings.xml
> +    <string name="categories">Categories</string>
И тут корректнее всего оставить название ресурса, например, для категории такого универсального вида: title_category. К названию строкового ресурса следует добавлять определенный префикс, чтобы название не тонуло в море других связанных с категорией элементов при глобальном поиске через Shift + cmd + F.

2024-07-25 08:10 UTC, ievetrovdev commented on app/src/main/res/values-en/strings.xml
> +    <string name="btn_favorite">Favorites</string>
с аналогичным названием для второго ресурса

2024-07-25 08:10 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="item_categoryTransparentBlack">#40000000</color>
смешение стилей именования айдишников недопустимо

2024-07-25 08:10 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="margin_medium">8dp</dimen>
тут 8

2024-07-25 08:10 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="corner_radius">8dp</dimen>
и тут 8

еще раз обращаю внимание. мы вообще не повторяем значения, а переиспользуем то что есть, группируя только если в стилях - при необходимости

2024-07-30 13:32 UTC, ievetrovdev approved these changes

2024-07-30 14:39 UTC, merged